
../plweb/includes/lecture-notes/IffyLang-Syntax-Eval.pdf : IffyLang/note.md
	cd IffyLang && make plweb

notes := ../plweb/includes/lecture-notes/IffyLang-Syntax-Eval.pdf

all : $(notes)

push : all
	cd .. && make push
